const types = {
  REGISTER: "REGISTER",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILED: "REGISTER_FAILED",

  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  LOGIN_WITH_GOOGLE: "LOGIN_WITH_GOOGLE",
  LOGIN_WITH_GOOGLE_SUCCESS: "LOGIN_WITH_GOOGLE_SUCCESS",
  LOGIN_WITH_GOOGLE_FAILED: "LOGIN_WITH_GOOGLE_FAILED",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",

  FORGOT_PASSWORD: "FORGOT_PASSWORD",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED",

  CHECK_RESET_PASSWORD_TOKEN: "CHECK_RESET_PASSWORD_TOKEN",
  CHECK_RESET_PASSWORD_TOKEN_SUCCESS: "CHECK_RESET_PASSWORD_TOKEN_SUCCESS",
  CHECK_RESET_PASSWORD_TOKEN_FAILED: "CHECK_RESET_PASSWORD_TOKEN_FAILED",

  RESET_PASSWORD: "RESET_PASSWORD",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED",

  SETTING_PASSWORD: "SETTING_PASSWORD",
  SETTING_PASSWORD_SUCCESS: "SETTING_PASSWORD_SUCCESS",
  SETTING_PASSWORD_FAILED: "SETTING_PASSWORD_FAILED",

  CHANGE_PASSWORD: "CHANGE_PASSWORD",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILED: "CHANGE_PASSWORD_FAILED",
};

export default types;
