const types = {
  GET_USERS: "GET_USERS",
  GET_USERS_SUCCESS: "GET_USERS_SUCCESS",
  GET_USERS_FAILED: "GET_USERS_FAILED",

  GET_USER: "GET_USER",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_FAILED: "GET_USER_FAILED",

  UPDATE_USER: "UPDATE_USER",
  UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
  UPDATE_USER_FAILED: "UPDATE_USER_FAILED",

  UPDATE_USERNAME: "UPDATE_USERNAME",
  UPDATE_USERNAME_SUCCESS: "UPDATE_USERNAME_SUCCESS",
  UPDATE_USERNAME_FAILED: "UPDATE_USERNAME_FAILED",

  UPDATE_EMAIL: "UPDATE_EMAIL",
  UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
  UPDATE_EMAIL_FAILED: "UPDATE_EMAIL_FAILED",
};

export default types;
