import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from 'next-intl/server';
import StoreProvider from "@/redux/store-provider";
import { Toaster } from "@/components/ui/sonner";
import Header from "./_view/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const messages = await getMessages();
  return (
    <StoreProvider>
      <html lang={locale} suppressHydrationWarning>
        <body className={`${inter.className} h-screen`}>
          <main className="flex min-h-screen flex-col items-center justify-start dark:bg-black">
            <ThemeProvider
              attribute="class"
              defaultTheme="light"
              enableSystem
              disableTransitionOnChange
            >
              <NextIntlClientProvider messages={messages}>
                <Header locale={locale}/>
                <div className="mt-[100px]"></div>
                {children}
                <Toaster richColors/>
              </NextIntlClientProvider> 
            </ThemeProvider>
          </main>
        </body>
      </html>
    </StoreProvider>
  );
}
